#define DEFAULT_JOB_NAME "NOPT_JOB"

#define BUF_LINE_LENGTH 1000

#define RHF_MAX_IT_DEFAULT 50
#define RHF_EN_CON_DEFAULT 1e-10
#define RHF_GR_CON_DEFAULT 1e-7

#define PRINT_DIPOLE 1
#define PRINT_DISP 0
#define PRINT_QUADRUPOLE 0
#define PRINT_MULLIKEN 0


#define CAS_MAX_IT_DEFAULT 50
#define CAS_EN_CON_DEFAULT 1e-10
#define CAS_GR_CON_DEFAULT 1e-7
#define CAS_STEP_CON_DEFAULT 1e-7
#define CAS_X_MAX_DEFAULT 0.1
#define CAS_PRINT_NUMBER_DEFAULT 10
#define CAS_METHOD_DEFAULT 1

#define DAV_MAX_IT_DEFAULT 250
#define DAV_EN_CON_DEFAULT 1e-10
#define DAV_R_CON_DEFAULT 5e-8
#define DAV_N_STATES_DEFAULT 10
#define DAV_N_STATES_MULT_DEFAULT 3
#define DAV_N_BF_DEFAULT 300
#define DAV_SE_MIN_DEFAULT 1e-8
#define DAV_ED_SHIFT_DEFAULT 0.03

#define XMC_N_FIT 300
#define XMC_N_FIT_POL 3
